### ISSUE TITLE
Update Broke - Weird Behaviour

### ISSUE THREAD

**Issue by GaddMaster** [kolodny/immutability-helper#177]
Hi

Struggling with this weird behaviour

It's simply understand my situation by reading the few lines of code and the few lines of console logs.

How is this happening, what on Earth am I missing here.

```
            console.log("Trying");
            console.log({ index });
            console.log(account.access);
            console.log(account.access[index]);
            const _access = updateHelper(account.access, {
                [0]: {
                    status: {
                        $set: "three"
                    }
                }
            });
            console.log({ _access });
```

```
Trying
{ index: 0 }
[{"userDBID":"61e92c4d82661c026e8c7fcd","type":"owner","status":"pending","position":"Managing Director"}]
{
  userDBID: '61e92c4d82661c026e8c7fcd',
  type: 'owner',
  status: 'pending',
  position: 'Managing Director'
}
error - TypeError: Class constructor CoreMongooseArray cannot be invoked without 'new'
    at copy (/Users/gaddbox/Documents/rentdodo/node_modules/immutability-helper/index.js:41:25)
    at /Users/gaddbox/Documents/rentdodo/node_modules/immutability-helper/index.js:104:38
    at Array.forEach (<anonymous>)
    at Context.update (/Users/gaddbox/Documents/rentdodo/node_modules/immutability-helper/index.js:85:26)
    at onAgencyVerified (webpack-internal:///./utils/server/contact.js:717:82)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async onVerifyCheckup (webpack-internal:///./utils/server/contact.js:557:34)
    at async handler (webpack-internal:///./pages/api/account/update/address.js:38:5)
    at async Object.apiResolver (/Users/gaddbox/Documents/rentdodo/node_modules/next/dist/server/api-utils.js:101:9)
    at async DevServer.handleApiRequest (/Users/gaddbox/Documents/rentdodo/node_modules/next/dist/server/next-server.js:770:9)
    at async Object.fn (/Users/gaddbox/Documents/rentdodo/node_modules/next/dist/server/next-server.js:661:37)
    at async Router.execute (/Users/gaddbox/Documents/rentdodo/node_modules/next/dist/server/router.js:205:32)
    at async DevServer.run (/Users/gaddbox/Documents/rentdodo/node_modules/next/dist/server/next-server.js:841:29)
    at async DevServer.run (/Users/gaddbox/Documents/rentdodo/node_modules/next/dist/server/dev/next-dev-server.js:355:20)
    at async DevServer.handleRequest (/Users/gaddbox/Documents/rentdodo/node_modules/next/dist/server/next-server.js:292:20) {
  page: '/api/account/update/address'
}
```

Daniel

**Comment by GaddMaster** [comment]
Tell me I am not going crazy ?
